//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowWaterCup.Services.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerAIStep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlayerAIStep()
        {
            this.PlayerAIStep1 = new HashSet<PlayerAIStep>();
        }
    
        public int AiId { get; set; }
        public Nullable<int> ParentStepId { get; set; }
        public int ActionTypeId { get; set; }
        public int PlayerAIStepId { get; set; }
    
        public virtual ActionType ActionType { get; set; }
        public virtual PlayerAI PlayerAI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerAIStep> PlayerAIStep1 { get; set; }
        public virtual PlayerAIStep PlayerAIStep2 { get; set; }
    }
}
