//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowWaterCup.Services.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerIAStep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlayerIAStep()
        {
            this.PlayerIAStep1 = new HashSet<PlayerIAStep>();
        }
    
        public int AiId { get; set; }
        public Nullable<int> ParentStepId { get; set; }
        public int ActionTypeId { get; set; }
        public int PlayerAIStepId { get; set; }
    
        public virtual ActionType ActionType { get; set; }
        public virtual PlayerIA PlayerIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerIAStep> PlayerIAStep1 { get; set; }
        public virtual PlayerIAStep PlayerIAStep2 { get; set; }
    }
}
