//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowWaterCup.Services.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShowWaterCupEntities : DbContext
    {
        public ShowWaterCupEntities()
            : base("name=ShowWaterCupEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionType> ActionTypes { get; set; }
        public virtual DbSet<Character> Characters { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<PlayerAI> PlayerAIs { get; set; }
        public virtual DbSet<PlayerAIStep> PlayerAISteps { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<Round> Rounds { get; set; }
        public virtual DbSet<Tournament> Tournaments { get; set; }
    }
}
